;; Terrific Audio Driver LoadSongData and audio driver/data .incbin statements.
;;
;; This file is automatically generated by `tad-compiler asar-export`.
;;
;; It MUST BE recreated if the audio project has changed (including samples, sound effects and songs).
;;

; SPDX-License-Identifier: Unlicense
;
; This is free and unencumbered software released into the public domain.
;
; Anyone is free to copy, modify, publish, use, compile, sell, or distribute this software, either in
; source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any
; means.
;
; In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any
; and all copyright interest in the software to the public domain. We make this dedication for the
; benefit of the public at large and to the detriment of our heirs and successors. We intend this
; dedication to be an overt act of relinquishment in perpetuity of all present and future rights to
; this software under copyright law.
;
; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
; NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
; NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
; WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
; SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
;
; For more information, please refer to <http://unlicense.org/>

!HIROM = 1
!TAD_IO_VERSION = 20

assert !TAD_IO_VERSION == 20, "TAD_IO_VERSION in audio driver does not match TAD_IO_VERSION in the asar-api"

!TAD_N_DATA_ITEMS = 25

assert bank(pc())|$80 >= $c0, "pc() not in a HIROM bank"
assert pc()&$ffff == $0000, "pc() does not start at the beginning of a HIROM bank"

;; LoadAudioData callback (HIROM mapping)
;;
;; Called using JSL (return with RTL)
;;
;; IN: A = 0 - Common audio data (MUST return carry set)
;; IN: A >= 1 - Song data (might be invalid)
;; OUT: Carry set if input (`A`) was valid
;; OUT: A:X = far address
;; OUT: Y = size
;; A8
;; I16
;; DP unknown
;; DB unknown
LoadAudioData: {
    assert defined("HIROM"), "memory map is not HIROM"
    assert !TAD_N_DATA_ITEMS > 1, "No common audio data"

    cmp.b   #!TAD_N_DATA_ITEMS
    bcc     +
        ; return false
        clc
        rtl
    +

    rep     #$30
; A16
    and.w   #$ff

    pha

    asl
    ; carry clear
    adc     1,s
    tax

    ; Calculate data size
    ; ASSUMES data size > 0 and <= $ffff
    lda.l   Tad_DataTable+3,x
    sec
    sbc.l   Tad_DataTable,x
    tay

    lda.l   Tad_DataTable,x
    sta     1,s

    sep     #$21
; A8
    lda.l   Tad_DataTable+2,x
    ; carry set
    adc.b   #(bank(Tad_DataTable)-1)&$ff

    plx

    sec
    rtl
}
assert pc()-LoadAudioData == 43, "LoadAudioData size mismatch"


assert filesize("example-project.bin") == 27360, "example-project.bin file size does not match binary size in the assembly file"


check bankcross off

Tad_AudioData:

Tad_Loader_Bin:
    incbin "example-project.bin":0..116
Tad_Loader_SIZE = 116

Tad_AudioDriver_Bin:
    incbin "example-project.bin":116..3337
Tad_AudioDriver_SIZE = 3221

;; [u24 ; !TAD_N_DATA_ITEMS] - table of PRG ROM offsets (from the start of the first Audio Data segment)
;; u16 footer - 16 bit clipped `bin_data_offset + bin_file.len()` (used to determine the size of the last item)
Tad_DataTable:
    incbin "example-project.bin":3337..27360

Tad_AudioData_End:

check bankcross full

